=== initia-labs/initia-registry/profile.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Chain Profile",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "pretty_name": {
      "type": "string"
    },
    "category": {
      "type": "string",
      "enum": ["DeFi", "Social", "NFT", "Gaming", "Portfolio", "AI", "Other"]
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 10
      },
      "maxItems": 3
    },
    "description": {
      "type": "string",
      "description": "A longer description for the landing page"
    },
    "summary": {
      "type": "string",
      "description": "A short description for the onboarding page (less than or equal to 50 characters)",
      "maxLength": 50
    },
    "color": {
      "$ref": "#/$defs/color",
      "description": "Modify saturation and luminance for the ecosystem or the vip"
    },
    "status": {
      "type": "string",
      "enum": ["live", "upcoming"]
    },
    "vip": {
      "type": "object",
      "properties": {
        "actions": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "title": {
                "type": "string"
              },
              "description": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "social": {
      "type": "object",
      "properties": {
        "website": {
          "type": "string",
          "format": "uri",
          "pattern": "^https://."
        },
        "twitter": {
          "type": "string",
          "format": "uri",
          "pattern": "^https://x.com/."
        }
      }
    },
    "l2": {
      "type": "boolean"
    }
  },
  "$defs": {
    "color": {
      "description": "RGB color",
      "format": "rgbcolor",
      "pattern": "^#([a-fA-F0-9]{6})$",
      "type": "string"
    }
  }
}

=== initia-labs/initia-registry/rehearsal/minimove/profile.json
{
  "$schema": "../../profile.schema.json",
  "name": "minimove",
  "pretty_name": "Minimove",
  "category": "Gaming",
  "l2": true,
  "description": "description",
  "summary": "summary",
  "color": "#42F771",
  "status": "live",
  "vip": {
    "actions": [
      {
        "title": "Earn Score",
        "description": "Scores will be randomly distributed to whitelisted addresses"
      }
    ]
  }
}

=== initia-labs/initia-registry/testnets/milkyway/profile.json
{
  "$schema": "../../profile.schema.json",
  "category": "DeFi",
  "l2": true,
  "description": "The Modular Staking Portal",
  "summary": "The Modular Staking Portal",
  "color": "#1E1B47",
  "status": "live",
  "vip": {
    "actions": [
      {
        "title": "Liquid stake",
        "description": "Bridging INIT from Initia to MilkyWay, and liquid staking those INIT tokens."
      }
    ]
  },
  "social": {
    "website": "https://www.milkyway.zone"
  }
}

=== initia-labs/initia-registry/testnets/ing/profile.json
{
  "$schema": "../../profile.schema.json",
  "name": "ing",
  "pretty_name": "Infinity Ground",
  "category": "Gaming",
  "tags": ["AI"],
  "l2": true,
  "description": "Enabling everyone to create interactive entertainment.",
  "summary": "Enabling everyone to create using AI & blockchain",
  "color": "#FFFFFF",
  "status": "live",
  "vip": {
    "actions": [
      {
        "title": "To be Infinity",
        "description": "Create a better future."
      }
    ]
  },
  "social": {
    "website": "https://www.infinityg.ai"
  }
}

=== initia-labs/initia-registry/testnets/cabal/profile.json
{
  "$schema": "../../profile.schema.json",
  "name": "cabal",
  "pretty_name": "Cabal",
  "category": "DeFi",
  "l2": false,
  "description": "The Very Important Protocol for Initia's VIP.",
  "color": "#54EEE7",
  "status": "upcoming",
  "social": {
    "website": "https://thecabal.xyz"
  }
}

=== initia-labs/initia-registry/testnets/yominet/profile.json
{
  "$schema": "../../profile.schema.json",
  "category": "Gaming",
  "l2": true,
  "description": "The first economically independent virtual world living onchain. Home to the Kamigotchi.",
  "summary": "Economically independent, onchain virtual world",
  "color": "#0A2311",
  "status": "live",
  "vip": {
    "actions": [
      {
        "title": "Complete Quest",
        "description": "Completing VIP quests in-game for each epoch."
      }
    ]
  },
  "social": {
    "website": "https://playtest.kamigotchi.io"
  }
}

=== initia-labs/initia-registry/testnets/minity/profile.json
{
  "$schema": "../../profile.schema.json",
  "name": "minity",
  "pretty_name": "Minity",
  "category": "Portfolio",
  "tags": ["Tooling"],
  "l2": false,
  "description": "Track your assets, DeFi Positions, and NFTs across every interwoven rollup.",
  "summary": "Track your assets and positions across L1 and L2s",
  "color": "#FFFFFF",
  "status": "live",
  "social": {
    "website": "https://minity.xyz"
  }
}

=== initia-labs/initia-registry/testnets/culinaris/profile.json
{
  "$schema": "../../profile.schema.json",
  "name": "culinaris",
  "pretty_name": "Battle for Blockchain",
  "category": "Gaming",
  "l2": true,
  "description": "Fully onchain battle world, where value gets redistributed based on players performance.",
  "summary": "Battle world, with value redistribution protocols.",
  "color": "#46BEFF",
  "status": "live",
  "vip": {
    "actions": [
      {
        "title": "Conquer Culinaris",
        "description": "Winning as much $BFB in-game for each war."
      }
    ]
  },
  "social": {
    "website": "https://battleforblockchain.com"
  }
}

=== initia-labs/initia-registry/testnets/infinityg/profile.json
{
  "$schema": "../../profile.schema.json",
  "name": "infinityg",
  "pretty_name": "Infinity Ground",
  "category": "Gaming",
  "tags": ["AI"],
  "l2": true,
  "description": "Enabling everyone to create interactive entertainment.",
  "summary": "Enabling everyone to create using AI & blockchain",
  "color": "#b387eb",
  "status": "live",
  "vip": {
    "actions": [
      {
        "title": "Complete Quest",
        "description": "Completing VIP quests in-game for each epoch."
      }
    ]
  },
  "social": {
    "website": "https://www.infinityg.ai"
  }
}
